### ISSUE TITLE
s24  / migrate data to Analitico Drive and fix recipes with catboost

### ISSUE THREAD

**Issue by danielebriggi** [analitico/analitico#303]
- [x] set drive
- [x] fix catboost, see: https://github.com/analitico/analitico/issues/310
- [x] fix order sorting, see: https://github.com/analitico/analitico/issues/310#issuecomment-515327586
- [x] migrate jobs #310 
- [x] rename rx and ds to v3
- [x] cron job https://github.com/analitico/analitico/issues/345
- [x] set_metric save into metadata.json https://github.com/analitico/analitico/issues/350
- [x] copy docs from s24 source folder to doc on recipe
